# Sample CI for conditional testing of /python and /mcp
name: CI

on:
  push:
    paths:
      - 'python/**'
      - 'mcp/**'
  pull_request:
    paths:
      - 'python/**'
      - 'mcp/**'

jobs:
  test-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm run test
      - name: Run integration tests
        run: pdm run integration
        env:
          DISCORD_BOTTOKEN: ${{ secrets.DISCORD_BOTTOKEN }}
          DISCORD_GET_MY_USER_OPERATION_UUID: e7ef41c27ac9dbd950a5079ff7a824a2
          DISCORD_GET_USER_DETAILS_WORKFLOW_UUID: 50b8c2a8d60ba2c66530e8dc55bbbe98

  test-mcp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcp
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm run test
