# Sample CI for conditional testing of /python and /mcp
name: CI

on:
  push:
    paths:
      - 'python/**'
      - 'mcp/**'
  pull_request:
    paths:
      - 'python/**'
      - 'mcp/**'

jobs:
  test-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm run pytest

  test-mcp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcp
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm run test
